---
# Global group variables

ansible_user: root
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3

# Common settings
ntp_enabled: true
selinux_state: disabled
firewall_enabled: true
